# Generated by Django 3.2.7 on 2021-09-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=150)),
                ('asset_description', models.CharField(max_length=150)),
                ('asset_owner', models.CharField(max_length=150)),
                ('created_by', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
